name: Fetch Email Attachments

on:
  workflow_dispatch:

permissions:
  contents: write   # allow pushing commits to the repo

jobs:
  fetch-attachments:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
      TARGET_SENDER: ${{ secrets.TARGET_SENDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required so we can commit back to the branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          # add more packages if needed

      - name: Run email fetch script
        run: python fetch_attachments.py

      - name: Upload attachments as artifact
        uses: actions/upload-artifact@v4
        with:
          name: email-attachments
          path: attachments/

      - name: Commit and push to main
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Copy attachments into tracked folder
          rm -rf email_attachments/*
          mkdir -p email_attachments
          cp -r attachments/* email_attachments/ || true

          git add email_attachments/
          git commit -m "Add new email attachments ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))" || echo "No changes to commit"
          git push origin HEAD:main
