name: Download iCloud Attachments

on:
  schedule:
    - cron: "0 9 * * *"  # every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install required Python libraries
      - name: Install dependencies
        run: pip install imapclient pyzmail36

      # Step 4: Run the Python script
      - name: Run main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          IMAP_PORT: ${{ secrets.IMAP_PORT }}
        run: python main.py

      # Step 5: Upload all attachments as GitHub artifacts
      - name: Upload attachments
        uses: actions/upload-artifact@v4
        with:
          name: paulo-attachments
          path: "attachments/*"
          retention-days: 7
