name: Run Python Script

on:
  schedule:
    - cron: "0 9 * * *"   # runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Python script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          IMAP_PORT: ${{ secrets.IMAP_PORT }}
          TARGET_SENDER: ${{ secrets.TARGET_SENDER }}
        run: python main.py

      - name: Upload all .xlsx attachments
        uses: actions/upload-artifact@v4
        with:
          name: paulo-attachments
          path: "*.xlsx"    # upload all .xlsx files from repo root
          retention-days: 7
