name: Download Gmail Attachments

on:
  schedule:
    - cron: "0 9 * * *"  # every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Run Python script
      - name: Run main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          IMAP_PORT: ${{ secrets.IMAP_PORT }}
          TARGET_SENDER: ${{ secrets.TARGET_SENDER }}
        run: python main.py

      # Upload attachments as artifacts
      - name: Upload attachments
        uses: actions/upload-artifact@v4
        with:
          name: paulo-attachments
          path: "attachments/*"
          retention-days: 7
