name: Fetch Email Attachments & Build Calendar

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 22:15 Lisbon time (UTC+1 assumed)
    - cron: '15 21 * * *'

permissions:
  contents: write

jobs:
  fetch-attachments:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
      TARGET_SENDER: ${{ secrets.TARGET_SENDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel pandas icalendar

      - name: Run email fetch script
        run: python fetch_attachments.py

      - name: Commit and push new attachments
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          rm -rf email_attachments/*
          mkdir -p email_attachments
          cp -r attachments/* email_attachments/ || true

          git add email_attachments/
          git commit -m "Update email attachments ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Build calendar
        run: python build_calendar.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: email-attachments-and-calendar
          path: |
            email_attachments/
            it.ics
