name: Fetch Email Attachments & Build Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: '15 18 * * *'

permissions:
  contents: write

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
      TARGET_SENDER: ${{ secrets.TARGET_SENDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel pandas icalendar openpyxl

      - name: Run fetch & build script
        run: python run.py

      - name: Commit files and calendar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p files
          git add files/
          git commit -m "Update files and calendar ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-and-calendar
          path: files/
